[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Daniel Bjerkehagen", email = "daniel.bjerkehagen@sintef.no"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

